import { createClient } from '@supabase/supabase-js'
import { env } from '@/config/env'

/**
 * Server-side Supabase client (uses anon key + RLS).
 *
 * For browser usage in the future (admin panel etc.), create a separate
 * client-side singleton — never reuse this one.
 */
export const supabase = createClient(env.supabaseUrl, env.supabaseAnonKey, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
})

// ─── Types ────────────────────────────────────────────────────────────

export interface UserRow {
  id: string // UUID generated by Supabase
  telegram_id: number
  username: string | null
  first_name: string | null
  last_name: string | null
  language_code: string | null
  balance_cr: number
  balance_sp: number
  level: number
  reputation: number
  successful_deals: number
  races_won: number
  races_total: number
  garage_slots: number
  created_at: string
  updated_at: string
}

export const NEW_USER_DEFAULTS = {
  balance_cr: 50_000,
  balance_sp: 0,
  level: 1,
  reputation: 0,
  successful_deals: 0,
  races_won: 0,
  races_total: 0,
  garage_slots: 3,
} as const
